### ISSUE TITLE
ob.omit matching all keys *containing* a string rather than exact match of string

### ISSUE THREAD

**Issue by StrangeWind** [chiedolabs/objob#1]
It would seem that, when using `ob.omit(myObject, ['my_key'])`, all keys in `myObject` that contain `'my_key'` are being omitted.

For example, given the following:

```javascript
myObject = {
  "my_key": "foo",
  "keeper": "bar",
  "my_key_keeper": "baz"
};
```
this call:

```javascript
ob.omit(myObject, ['my_key'])
```
will return this:

```javascript
{
   "keeper": "bar"
}
```
even though I was expecting:

```javascript
{
  "keeper": "bar",
  "my_key_keeper": "baz"
}
```

It is possible that this behavior is specific to using ob.omit as part of a [Swag Doctor](https://github.com/chiedolabs/swag-doctor) module - I didn't dig that deep. :)

**Comment by chiedo** [comment]
Hey man! 
Are you using the latest version of objob?

I was pretty sure I patched that issue a few days ago.

If you're using the latest version l, I'll look into it again though! :)

**Comment by chiedo** [comment]
I'll wait for your response. If you're still having the issue and you're on the latest version, I'm pretty sure I hair used a regex that checked for a-Z and 0-9 and also need to check for _ and $

**Comment by StrangeWind** [comment]
I show that I'm running objob@2.7.9

I looked at your regex, and like you say, it may not be casting a wide enough net.

If it helps, my actual keys are `elements` and `elements_board_id`.

**Comment by chiedo** [comment]
I'll look into it then! :) in the meantime, Lodash had the same functions, with the only difference being that they're shallow! But should work for your needs

**Comment by StrangeWind** [comment]
I'm okay just ob.pick()'ing everything but my omitted key for now. :) Just wanted to bring it to your attention for whenever.

**Comment by chiedo** [comment]
Thanks man! :)

**Comment by chiedo** [comment]
This issue should now be patched!

My logic was right but I didn't escape enough times in my regex so while I thought I was checking for a period, I was checking for all characters.

Before:
```
let re = new RegExp('^'+inputKey+'\..*','g');
```

After:
```
let re = new RegExp('^'+inputKey+'\\..*','g');
```
